package com.GrupoProga3.Gestor_Salud.auth.permisos;

public enum PERMISOS {
    CREAR_PACIENTE,
    VER_PACIENTE,
    EDITAR_PACIENTE,
    ELIMINAR_PACIENTE,

    CREAR_HISTORIA_CLINICA,
    VER_HISTORIA_CLINICA,

    CREAR_TURNO,
    EDITAR_TURNO,
    CANCELAR_TURNO,

    CREAR_RECETA,
    VER_RECETA,

    CREAR_DIAGNOSTICO,
    EDITAR_DIAGNOSTICO,

    CREAR_TRATAMIENTO,
    EDITAR_TRATAMIENTO,

    CREAR_MEDICAMENTO,
    VER_MEDICAMENTO,
    EDITAR_MEDICAMENTO,
    ELIMINAR_MEDICAMENTO,

    CREAR_PAGO,
    VER_PAGO,

    CREAR_PROVEEDOR,
    VER_PROVEEDOR,
    COMUNICAR_PROVEEDOR,

    GESTIONAR_USUARIO
}
