package com.GrupoProga3.Gestor_Salud.auth.permisos;

public enum PERMISOS {
    CREAR_PACIENTE,
    VER_PACIENTE,
    EDITAR_PACIENTE,
    ELIMINAR_PACIENTE,
    INTERNAR_PACIENTE,

    CREAR_HISTORIA_CLINICA,
    VER_HISTORIA_CLINICA,
    EDITAR_HISTORIA_CLINICA,

    VER_TURNO,
    VER_TURNO_FACTURABLE,
    CREAR_TURNO,
    EDITAR_TURNO,
    CANCELAR_TURNO,

    CREAR_RECETA,
    VER_RECETA,

    CREAR_DIAGNOSTICO,
    VER_DIAGNOSTICO,
    EDITAR_DIAGNOSTICO,

    CREAR_TRATAMIENTO,
    VER_TRATAMIENTO,
    EDITAR_TRATAMIENTO,
    ASIGNAR_TRATAMIENTO,

    CREAR_MEDICAMENTO,
    VER_MEDICAMENTO,
    EDITAR_MEDICAMENTO,
    ELIMINAR_MEDICAMENTO,

    CREAR_PAGO,
    VER_PAGO,

    CREAR_GASTO,
    EDITAR_GASTO,
    VER_GASTO,
    ELIMINAR_GASTO,

    CREAR_FACTURA,
    EDITAR_PAGO,
    VER_FACTURA,
    ELIMINAR_PAGO,

    CREAR_PROVEEDOR,
    EDITAR_PROVEEDOR,
    ELIMINAR_PROVEEDOR,
    VER_PROVEEDOR,
    COMUNICAR_PROVEEDOR,

    VER_USUARIO,
    VER_PROFESIONAL,
    GESTIONAR_USUARIO,

    CREAR_SALA,
    EDITAR_SALA,
    VER_SALA,

    CREAR_OBRA_SOCIAL,
    EDITAR_OBRA_SOCIAL,
    VER_OBRA_SOCIAL,
    ELIMINAR_OBRA_SOCIAL,

    VER_DOMICILIO,
    EDITAR_DOMICILIO,
    ELIMINAR_DOMICILIO,

    VER_CONTACTO,
    CREAR_CONTACTO,
    EDITAR_CONTACTO,
    ELIMINAR_CONTACTO,

    CREAR_CIRUGIA,
    EDITAR_CIRUGIA,
    VER_CIRUGIA,
    ELIMINAR_CIRUGIA
}
